<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AshkanSocial.Application\AshkanSocial.Application.csproj" />
    <ProjectReference Include="..\AshkanSocial.Infrastructure\AshkanSocial.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Forms\Main\" />
    <Folder Include="Controls\" />
    <Folder Include="Resources\" />
    <Folder Include="Themes\" />
	<None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  </PackageReference>
  <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
  <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.11" />
  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>

</Project>